// console.log("1" == 1)
// console.log(true == 1)
// console.log(true == undefined)
// console.log(null == undefined)
// console.log(null == false)
// console.log(undefined == false)
// console.log(undefined == true)
// console.log("" == 0)        
// console.log("1,2" != [1,2])
// console.log(undefined === "")
// console.log(1 === "1")
console.log(1 != "1")